version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - 'Type: Dependencies'
    commit-message:
      prefix: chore(Security)
    rebase-strategy: auto
