const SHEET_ARROW_POSITION = {
  LEFT_BOTTOM: 'left_bottom',
  TOP_RIGHT: 'top_right',
} as const

const SHEET_PLACEMENT = {
  BELOW: 'below',
  RIGHT: 'right',
} as const

const SHEET_PLACEMENT_ARROW_POSITION_MAP = {
  [SHEET_PLACEMENT.BELOW]: SHEET_ARROW_POSITION.TOP_RIGHT,
  [SHEET_PLACEMENT.RIGHT]: SHEET_ARROW_POSITION.LEFT_BOTTOM,
}

export {
  SHEET_ARROW_POSITION,
  SHEET_PLACEMENT,
  SHEET_PLACEMENT_ARROW_POSITION_MAP,
}
