import React from 'react'
import { storiesOf } from '@storybook/react'

import {
  Badge,
  BADGE_COLOR,
  BADGE_COLOR_VARIANT,
  BADGE_SIZE,
  BADGE_VARIANT,
} from '.'

const stories = storiesOf('Badge', module)

stories.add('Faded', () => (
  <div>
    <Badge
      color={BADGE_COLOR.NEUTRAL}
      colorVariant={BADGE_COLOR_VARIANT.FADED}
      size={BADGE_SIZE.REGULAR}
    >
      Neutral
    </Badge>
    <Badge
      color={BADGE_COLOR.ACTION}
      colorVariant={BADGE_COLOR_VARIANT.FADED}
      size={BADGE_SIZE.REGULAR}
    >
      Action
    </Badge>
    <Badge
      color={BADGE_COLOR.DANGER}
      colorVariant={BADGE_COLOR_VARIANT.FADED}
      size={BADGE_SIZE.REGULAR}
    >
      Danger
    </Badge>
    <Badge
      color={BADGE_COLOR.WARNING}
      colorVariant={BADGE_COLOR_VARIANT.FADED}
      size={BADGE_SIZE.REGULAR}
    >
      Warning
    </Badge>
    <Badge
      color={BADGE_COLOR.SUCCESS}
      colorVariant={BADGE_COLOR_VARIANT.FADED}
      size={BADGE_SIZE.REGULAR}
    >
      Success
    </Badge>
  </div>
))

stories.add('Solid', () => (
  <div>
    <Badge
      color={BADGE_COLOR.NEUTRAL}
      colorVariant={BADGE_COLOR_VARIANT.SOLID}
      size={BADGE_SIZE.REGULAR}
    >
      Neutral
    </Badge>
    <Badge
      color={BADGE_COLOR.ACTION}
      colorVariant={BADGE_COLOR_VARIANT.SOLID}
      size={BADGE_SIZE.REGULAR}
    >
      Action
    </Badge>
    <Badge
      color={BADGE_COLOR.DANGER}
      colorVariant={BADGE_COLOR_VARIANT.SOLID}
      size={BADGE_SIZE.REGULAR}
    >
      Danger
    </Badge>
    <Badge
      color={BADGE_COLOR.WARNING}
      colorVariant={BADGE_COLOR_VARIANT.SOLID}
      size={BADGE_SIZE.REGULAR}
    >
      Warning
    </Badge>
    <Badge
      color={BADGE_COLOR.SUCCESS}
      colorVariant={BADGE_COLOR_VARIANT.SOLID}
      size={BADGE_SIZE.REGULAR}
    >
      Success
    </Badge>
  </div>
))

stories.add('Sizes', () => (
  <div>
    <Badge
      color={BADGE_COLOR.NEUTRAL}
      colorVariant={BADGE_COLOR_VARIANT.FADED}
      size={BADGE_SIZE.SMALL}
    >
      Small
    </Badge>
    <Badge
      color={BADGE_COLOR.NEUTRAL}
      colorVariant={BADGE_COLOR_VARIANT.FADED}
      size={BADGE_SIZE.REGULAR}
    >
      Regular
    </Badge>
    <Badge
      color={BADGE_COLOR.NEUTRAL}
      colorVariant={BADGE_COLOR_VARIANT.FADED}
      size={BADGE_SIZE.LARGE}
    >
      Large
    </Badge>
    <Badge
      color={BADGE_COLOR.NEUTRAL}
      colorVariant={BADGE_COLOR_VARIANT.FADED}
      size={BADGE_SIZE.XLARGE}
    >
      XLarge
    </Badge>
  </div>
))

stories.add('Pills', () => (
  <div>
    <Badge
      color={BADGE_COLOR.NEUTRAL}
      colorVariant={BADGE_COLOR_VARIANT.SOLID}
      size={BADGE_SIZE.REGULAR}
      variant={BADGE_VARIANT.PILL}
    >
      Neutral
    </Badge>
    <Badge
      color={BADGE_COLOR.ACTION}
      colorVariant={BADGE_COLOR_VARIANT.SOLID}
      size={BADGE_SIZE.REGULAR}
      variant={BADGE_VARIANT.PILL}
    >
      Action
    </Badge>
    <Badge
      color={BADGE_COLOR.DANGER}
      colorVariant={BADGE_COLOR_VARIANT.SOLID}
      size={BADGE_SIZE.REGULAR}
      variant={BADGE_VARIANT.PILL}
    >
      Danger
    </Badge>
    <Badge
      color={BADGE_COLOR.WARNING}
      colorVariant={BADGE_COLOR_VARIANT.SOLID}
      size={BADGE_SIZE.REGULAR}
      variant={BADGE_VARIANT.PILL}
    >
      Warning
    </Badge>
    <Badge
      color={BADGE_COLOR.SUCCESS}
      colorVariant={BADGE_COLOR_VARIANT.SOLID}
      size={BADGE_SIZE.REGULAR}
      variant={BADGE_VARIANT.PILL}
    >
      Success
    </Badge>
  </div>
))
