name: Set up Node.js and install dependencies
description: Sets up Node.js and installs dependencies
inputs:
  unpack-prebuilt-libraries:
    description: Whether to unpack pre-built icon-library and design-tokens bundles
    required: false
    default: ''
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v3
      with:
        version: 9.1.1
        run_install: false
        standalone: true

    - uses: actions/setup-node@v4
      with:
        node-version: 18.20.1
        node-version-file: .nvmrc
        cache: pnpm

    - name: Cache Node modules
      uses: actions/cache@v4
      with:
        path: '**/node_modules'
        key: node-modules-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: Install dependencies
      shell: bash
      run: |
        pnpm install --frozen-lockfile --ignore-scripts

    - name: Download icon-library and design-tokens
      if: inputs.unpack-prebuilt-libraries
      uses: actions/download-artifact@v4
      with:
        name: dist

    - name: Unpack icon-library and design-tokens
      if: inputs.unpack-prebuilt-libraries
      shell: bash
      run: |
        tar -xzf dist.tar.gz && mv distil packages/icon-library/dist && mv distdt packages/design-tokens/dist
