name: Set up Node.js and install dependencies
description: Sets up Node.js and installs dependencies
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: yarn

    - name: Cache Node modules
      uses: actions/cache@v3
      with:
        path: '**/node_modules'
        key: node-modules-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

    - name: Cache Cypress binary
      uses: actions/cache@v3
      with:
        path: ~/.cache/Cypress
        key: cypress-${{ runner.os }}-cypress-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          cypress-${{ runner.os }}-cypress-

    - name: Install dependencies
      shell: bash
      run: |
        yarn install --frozen-lockfile
