const LOCALE = {
  UK: 'en-GB',
}

const DATEPICKER_AUTO_CLOSE_DELAY = 0

const WEEKDAY_TITLES = ['SUN', 'MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT']

export { DATEPICKER_AUTO_CLOSE_DELAY, LOCALE, WEEKDAY_TITLES }
