const SHEET_ARROW_POSITION = {
  LEFT_BOTTOM: 'left_bottom',
  LEFT_TOP: 'left_top',
  TOP_RIGHT: 'top_right',
} as const

const SHEET_PLACEMENT = {
  BELOW: 'below',
  RIGHT_BOTTOM: 'right_bottom',
  RIGHT_TOP: 'right_top'
} as const

const SHEET_PLACEMENT_ARROW_POSITION_MAP = {
  [SHEET_PLACEMENT.BELOW]: SHEET_ARROW_POSITION.TOP_RIGHT,
  [SHEET_PLACEMENT.RIGHT_BOTTOM]: SHEET_ARROW_POSITION.LEFT_BOTTOM,
  [SHEET_PLACEMENT.RIGHT_TOP]: SHEET_ARROW_POSITION.LEFT_TOP,
}

export {
  SHEET_ARROW_POSITION,
  SHEET_PLACEMENT,
  SHEET_PLACEMENT_ARROW_POSITION_MAP,
}
