name: Build & Test

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  Build_icon_library:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone repository
        uses: actions/checkout@v3

      - name: Set up environment
        uses: ./.github/actions/prepare-environment

      - name: Build icon-library
        run: |
          yarn --cwd packages/icon-library build

      - name: Build design-tokens
        run: yarn --cwd packages/design-tokens build

      - name: Create tar
        run: |
          cp -R packages/icon-library/dist distil
          cp -R packages/design-tokens/dist distdt
          tar -czvf dist.tar.gz distil distdt

      - name: Persist artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./dist.tar.gz

  Security_audit:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone repository
        uses: actions/checkout@v3

      - name: Run audit
        run: yarn run audit

  Check_commits:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Git clone repository
        uses: actions/checkout@v3

      - name: Set up environment
        uses: ./.github/actions/prepare-environment

      - name: check commits
        run: |
          node ./scripts/commitlint ${{ github.event.pull_request._links.html.href }}
          node ./scripts/check-fixup ${{ github.event.pull_request._links.html.href }}

  Lint_react-component-library:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone repository
        uses: actions/checkout@v3

      - name: Set up environment
        uses: ./.github/actions/prepare-environment

      - name: Get dependencies & run lint
        run: |
          yarn --cwd packages/react-component-library lint

  Test_react-component-library:
    runs-on: ubuntu-latest
    needs: [Build_icon_library, Lint_react-component-library]
    steps:
      - name: Git clone repository
        uses: actions/checkout@v3

      - name: Set up environment
        uses: ./.github/actions/prepare-environment

      - name: Attach workspace
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Jest
        env:
          JEST_JUNIT_OUTPUT_DIR: test-results/jest
          JEST_JUNIT_OUTPUT_NAME: react-component-results.xml
        run: |
          tar -xzf dist.tar.gz && mv distil packages/icon-library/dist && mv distdt packages/design-tokens/dist
          yarn --cwd packages/react-component-library test --ci --coverage --silent --no-cache --reporters=default --reporters=jest-junit --runInBand --testResultsProcessor=jest-sonar-reporter

      - name: SonarCloud Scan
        uses: defencedigital/design-system-sonarcloud-action@master
        if: (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository) && github.actor != 'dependabot[bot]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  Test-e2e_react-component-library:
    runs-on: ubuntu-latest
    needs: [Build_icon_library, Lint_react-component-library]
    strategy:
      matrix:
        browser: ['chrome', 'firefox']
    steps:
      - name: Git clone repository
        uses: actions/checkout@v3

      - name: Set up environment
        uses: ./.github/actions/prepare-environment

      - name: Attach workspace
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Unpack icon library & design tokens
        run: |
          tar -xzf dist.tar.gz && mv distil packages/icon-library/dist && mv distdt packages/design-tokens/dist

      - name: Confirm Cypress binary is installed
        run: |
          result=$(yarn cypress version)
          if [[  `echo $result` == *"not installed"* ]];
            then echo "cypress binary is not installed, installing binary...." && yarn cypress install;
            else echo "cypress binary is installed, no action required";
          fi

      - name: Run e2e tests
        uses: cypress-io/github-action@v4
        env:
          CHOKIDAR_USEPOLLING: 1
        with:
          project: ./packages/react-component-library
          start: yarn --cwd packages/react-component-library storybook:test
          wait-on: 'http://localhost:6006'
          wait-on-timeout: 180
          browser: ${{ matrix.browser }}

  Test_design-tokens:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone repository
        uses: actions/checkout@v3

      - name: Set up environment
        uses: ./.github/actions/prepare-environment

      - name: Jest design-tokens
        run: |
          yarn --cwd packages/design-tokens build
          yarn --cwd packages/design-tokens test

  # See post_built_and_test.yml for details about how this is used
  Build_storybook:
    runs-on: ubuntu-latest
    needs: [Build_icon_library, Lint_react-component-library]
    steps:
      - name: Git clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up environment
        uses: ./.github/actions/prepare-environment

      - name: Attach workspace
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Build Storybook
        env:
          CHROMATIC_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
          CHROMATIC_BRANCH: ${{ github.head_ref || github.ref_name }}
          CHROMATIC_SLUG: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
        run: |
          tar -xzf dist.tar.gz && mv distil packages/icon-library/dist && mv distdt packages/design-tokens/dist
          yarn --cwd packages/react-component-library storybook:static
          echo "$CHROMATIC_SHA" > packages/react-component-library/.static_storybook/sha
          echo "$CHROMATIC_BRANCH" > packages/react-component-library/.static_storybook/branch
          echo "$CHROMATIC_SLUG" > packages/react-component-library/.static_storybook/slug

      - name: Upload Storybook artefact
        uses: actions/upload-artifact@v3
        with:
          name: storybook-static
          path: packages/react-component-library/.static_storybook

  Test_a11y:
    runs-on: ubuntu-latest
    needs: [Build_storybook]
    steps:
      - name: Git clone repository
        uses: actions/checkout@v3

      - name: Set up environment
        uses: ./.github/actions/prepare-environment

      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: '~/.cache/ms-playwright'
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/yarn.lock') }}

      - name: Attach workspace
        uses: actions/download-artifact@v3
        with:
          name: storybook-static
          path: packages/react-component-library/.static_storybook

      - name: Set up Playwright
        run: |
          npm exec --no -- playwright install --with-deps chromium

      - name: Run accessibility tests
        run: |
          npm exec --no -- concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npm exec --no -- http-server packages/react-component-library/.static_storybook --port 6006 --silent" \
            "npm exec --no -- wait-on tcp:6006 && yarn  --cwd packages/react-component-library test:a11y"
