name: Check Commits

on: pull_request

jobs:
  Check_commits:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone repository
        uses: actions/checkout@v2

      - name: Cache Node modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Check commits
        run: |
          node ./scripts/commitlint ${{ github.event.pull_request._links.html.href }}
          node ./scripts/check-fixup ${{ github.event.pull_request._links.html.href }}
